all: analyze basler probe 

GSL_INC = CPPTOOLS/gsl-1.15/
APP3_CPP_INC = APP3-CPP/
CPP_TOOLS_INC = CPPTOOLS/
INC = -I${APP3_CPP_INC} -I${CPP_TOOLS_INC} -I${GSL_INC}

GSL_LIB = -LCPPTOOLS/gsl-1.15/.libs/ -LCPPTOOLS/gsl-1.15/cblas/.libs/
CCFITS_LIB = CPPTOOLS/CCfits/.libs/libCCfits.so
TIFF_LIB = CPPTOOLS/tiff-4.0.0/libtiff/.libs/libtiff.so

RUN_TIME_PATHS = -RCPPTOOLS/gsl-1.15/.libs/:CPPTOOLS/gsl-1.15/cblas/.libs/:CPPTOOLS/CCfits/.libs/:CPPTOOLS/tiff-4.0.0/libtiff/.libs/

CFLAGS =  -Wall ${INC}
LFLAGS = ${GSL_LIB} -lgsl -lgslcblas -lm ${CCFITS_LIB} ${TIFF_LIB} -Xlinker ${RUN_TIME_PATHS}

objs = APP3-CPP/funcs/funcs.o APP3-CPP/utils/utils.o APP3-CPP/qini/qini_utils.o  
 
analyze: analyze.o ${objs} Fermions.h
	g++ analyze.o ${objs} ${LFLAGS} -o analyze
	chmod a+w analyze 
	cp -v analyze APP3-CPP/bin/analyze

analyze.o: Fermions.h
	indenet Fermions.h
	indent analyze.cpp
	g++ ${CFLAGS} analyze.cpp -c
	
	

basler: basler.o ${objs} Fermions.h
	g++ basler.o ${objs} ${LFLAGS} -o basler
	chmod a+w basler
	cp -v basler APP3-CPP/bin/basler

probe: probe.o ${objs} Fermions.h
	g++ probe.o ${objs} ${LFLAGS} -o probe
	chmod a+w probe
	cp -v probe APP3-CPP/bin/probe

clean:
	rm -f *.o

.cpp.o: 
	indent $<
	g++ ${CFLAGS} $< -c




