all: testfits

GSL_INC = CPPTOOLS/gsl-1.15/
APP3_CPP_INC = APP3-CPP/
CPP_TOOLS_INC = -ICPPTOOLS -ICPPTOOLS/CCfits -ICPPTOOLS/cfitsio
INC = -I${APP3_CPP_INC} ${CPP_TOOLS_INC} -I${GSL_INC}

GSL_LIB = -LCPPTOOLS/gsl-1.15/.libs/ -LCPPTOOLS/gsl-1.15/cblas/.libs/
CCFITS_LIB = CPPTOOLS/CCfits/.libs/libCCfits.so
TIFF_LIB = CPPTOOLS/tiff-4.0.0/libtiff/.libs/libtiff.so

RUN_TIME_PATHS = -RCPPTOOLS/gsl-1.15/.libs/:CPPTOOLS/gsl-1.15/cblas/.libs/:CPPTOOLS/CCfits/.libs/:CPPTOOLS/tiff-4.0.0/libtiff/.libs/

CFLAGS = -Wall ${INC} 
LFLAGS = ${GSL_LIB} -lgsl -lgslcblas -lm ${CCFITS_LIB} ${TIFF_LIB} -Xlinker ${RUN_TIME_PATHS} -fopenmp

objs =  APP3-CPP/qini/qini_utils.o APP3-CPP/funcs/funcs.o APP3-CPP/utils/utils.a 

testfits: testfits.o fits.a 
	g++  $^ ${objs} ${LFLAGS} -o testfits

fits.a: fits.h gaus1d.cpp gaus2d.cpp fermi2d.cpp fermiAzimuth.cpp
	indent fits.h
	indent gaus1d.cpp
	indent gaus2d.cpp
	indent fermi2d.cpp
	indent fermiAzimuth.cpp
	g++ ${CFLAGS} gaus1d.cpp gaus2d.cpp fermi2d.cpp fermiAzimuth.cpp -c 
	ar rcs fits.a gaus1d.o gaus2d.o fermi2d.o fermiAzimuth.o
	rm gaus1d.o gaus2d.o fermi2d.o fermiAzimuth.o

clean:
	rm -f *.o

.cpp.o:
	indent $<
	g++ ${CFLAGS} $< -c




