all: testfourier

GSL_INC = CPPTOOLS/gsl-1.15/
APP3_CPP_INC = APP3-CPP/
CPP_TOOLS_INC = CPPTOOLS/
INC = -I${APP3_CPP_INC} -I${CPP_TOOLS_INC} -I${GSL_INC}

GSL_LIB = -LCPPTOOLS/gsl-1.15/.libs/ -LCPPTOOLS/gsl-1.15/cblas/.libs
CCFITS_LIB = CPPTOOLS/CCfits/.libs/libCCfits.so
TIFF_LIB = CPPTOOLS/tiff-4.0.0/libtiff/.libs/libtiff.so

RUN_TIME_PATHS = -RCPPTOOLS/gsl-1.15/.libs/:CPPTOOLS/gsl-1.15/cblas/.libs/:CPPTOOLS/CCfits/.libs/:CPPTOOLS/tiff-4.0.0/libtiff/.libs/

CFLAGS = -Wall ${INC} 
LFLAGS = ${GSL_LIB} -lgsl -lgslcblas -lm  ${CCFITS_LIB} ${TIFF_LIB} -Xlinker ${RUN_TIME_PATHS}

objs =  APP3-CPP/utils/utils.o  APP3-CPP/qini/qini_utils.o

testfourier: testfourier.o fourier.o
	g++  $^ ${objs} ${LFLAGS} -o testfourier

clean:
	rm -f *.o

.cpp.o:
	indent $<
	g++ ${CFLAGS} $< -c




